version: '{build}'
skip_tags: true
image:
  - Visual Studio 2017
  - Ubuntu
configuration: Release
test: off
build_script:
  - ps: ./Build.ps1
  - ps: ./BuildNativeUWP.ps1
for:
-
  matrix:
    only:
      - image: Ubuntu
  build_script:
  - sh build.sh
artifacts:
  - path: artifacts/Serilog.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: oy2gyl6ljt7q7un4joiqkln6zdwm74auplm4k5pl4nr2e4
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
- provider: GitHub
  auth_token:
    secure: p4LpVhBKxGS5WqucHxFQ5c7C8cP74kbNB0Z8k9Oxx/PMaDQ1+ibmoexNqVU5ZlmX
  artifact: /Serilog.*\.nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: master
